server:
  port: 8888
job:
  notice:
    cron:
      web: 0 0/30 * * * ?
      ssh: 0 0/30 * * * ?
file:
  path:
    log:
      web: /home/pi/log/web.log
      ssh: /home/pi/log/ssh.log
spring:
  mail:
    host: imap.qq.com
    username: 791465939@qq.com
    password: euoccddhkarsbegf
#    password: xie83292070
    properties:
      from: 791465939@qq.com
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    mode: HTML
    suffix: .html
target:
  mail: xiechongyang7@163.com
shell:
  path: /home/pi/pi/ng.sh
nginx:
  config:
    path: /etc/nginx/conf.d/server.conf
    root:
#job.log.cron=0 0/30 * * * ?
#file.path.log,info=