server:
  port: 8888
job:
  notice:
    cron: 0 0/5 * * * ?
file:
  path:
    log:
      web: /home/pi/log/web.log
      ssh: /home/pi/log/ssh.log
spring:
  mail:
    host: imap.qq.com
    username: 791465939@qq.com
    password: euoccddhkarsbegf
#    password: xie83292070
    properties:
      from: 791465939@qq.com

target:
  mail: xiechongyang7@163.com
shell:
  path: /home/pi/pi/ng.sh
nginx:
  config:
    path: /etc/nginx/conf.d/server.conf
#job.log.cron=0 0/30 * * * ?
#file.path.log,info=
